# Generated by Django 5.1 on 2024-08-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_doctorprofile_pharmacyprofile_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dosage_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generics_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmaceutical_Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('item_code', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=60)),
                ('strength', models.CharField(max_length=80)),
                ('dosage_form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosage_med', to='prescription.dosage_form')),
                ('generics_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_med', to='prescription.generics_names')),
                ('pharmaceutical_com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmaceutical_med', to='prescription.pharmaceutical_companies')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_no', models.CharField(blank=True, max_length=50, null=True)),
                ('prescription_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='user.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(choices=[('1+0+0', '1+0+0'), ('1+1+0', '1+1+0'), ('1+1+1', '1+1+1'), ('0+1+0', '0+1+0'), ('0+1+1', '0+1+1'), ('0+0+1', '0+0+1'), ('1+0+1', '1+0+1'), ('1+1+1+1', '1+1+1+1')], max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('meal_instructions', models.CharField(blank=True, choices=[('before_meal', 'Before Meal'), ('after_meal', 'After Meal')], max_length=50, null=True)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.brand_name')),
                ('condition_instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescription.conditioninstruction')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescription.prescription')),
            ],
        ),
    ]
